### PR TITLE
Change page transactions display

### LINKED ISSUE #92: Change PageTransactions display: move all messages together.
"I was hoping the display of multiple msgs inside a tx could work out, so they would exist within the same container (rounded corners) as below, but just with 1 container and not 3. Each msg taking a single row, and then the tx fees and memo shown below the last msg.

Perhaps each row/msg could have a an alternating background color, such as white/light-grey, to make it easier to distinguish them. First row could be white, as in 99.5% of cases there will ever only be a single msg per tx, making it look similar to what we have today."

*Also display Fees and Memo on the footer of the transaction item.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #92 

Screenshot taken exploring with address emoney1cpfn66xumevrx755m4qxgezw9j5s86qkan5ch8

image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Exploring with emoney1n6kqrlmdhenstppxuaemczplnex0cyk9ddm3yd

image

**Comment by mdyring** [comment]
Looks good, maybe we can remove the "popup" icon as it is not relevant per message (and clicking the container will open popup anyway)
image

Also let's just stick with the "Fee:" and remove the trailing "eNOK fee"

image

**Comment by Bitcoinera** [comment]
> Looks good, maybe we can remove the "popup" icon as it is not relevant per message (and clicking the container will open popup anyway)

We could have one per transaction. Probably on the top right corner would be its place. It is important to have something telling users they will be taken somewhere if they click there.

> Also let's just stick with the "Fee:" and remove the trailing "eNOK fee"

I would remove just "fee". It is important to know in which denom you are paying those fees

**Comment by mdyring** [comment]
> We could have one per transaction. Probably on the top right corner would be its place. It is important to have something telling users they will be taken somewhere if they click there.

Good point, yes let's try top right corner

>  would remove just "fee". It is important to know in which denom you are paying those fees

Yep, thats what I meant. We should keep denom just wanted to remove the last "fee" - this will also make amounts align nicely :-)

**Comment by Bitcoinera** [comment]
Suggestions applied!

image

**Pull request merged**
