### PR TITLE
Ana/2 reorganisation

### LINKED ISSUE #2: Reorganisation
New structure outlined below. First iteration without Market page.

| Menu item | Page content | Notes |
|---|---|---|
|Portfolio  |"Your Balances" followed by "Transactions" |"Claim Rewards" button moves to Staking page. Send buttons per row are removed and replaced by a "Send" button where "Claim Rewards" used to be.
|Stake |"Your Stake" followed by "Validators" list |"Claim Rewards" button placed above "Your Stake".
|Validators |None | Menu item is removed. Validators listed on "Staking" page instead.
|Swap | "Your Orders" followed by "Market Orders"|There should be a "New  Order" button above "Your Orders", and a button on each row of user orders to cancel them.|

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #2 

Maybe we should keep Transactions though. Not sure if it is a good idea to remove that option, especially if we add new features to it, like Filter and CSV Export.

Portfolio:

image

Stake:

image

Market:

image

### CODE REVIEW

**Comment by mdyring** [comment]
Looks good!

1) Please move "Claim rewards" from Portfolio -> Stake page

2) Yeah, agree we should keep Transactions page for the planned added functionality.

3) I think it is nicer if we remove transactions from the "Portfolio" page again to give it a cleaner look. 

4) We can later add a graph to Portfolio page that shows account balances over time (one line per denom)? (similar to Ledger Live)

**Comment by Bitcoinera** [comment]
> 1. Please move "Claim rewards" from Portfolio -> Stake page

We could have it in both pages. It is also handy to have it there, right on Portfolio, as one of the first actions you land to

**Comment by mdyring** [comment]
Looks good - comments:

1) Please horizontaly align "Your Stake" table with the table below (all validators)
2) Please add a "All Validators" title to the bottom section
3) Please remove "Claim rewards" from portfolio page (I see it is already on "Stake" page)
4) Please rename "Market" to "Swap" (to make it a verb similar to "Stake")

**Comment by Bitcoinera** [comment]
> 1. Please horizontally align "Your Stake" table with the table below (all validators)

You mean vertically, right? :eyes:

**Comment by Bitcoinera** [comment]
This is how it is looking now

image

**Comment by Bitcoinera** [comment]
I think I will rename all the "markets" to "swap", so it stays consistent

**Comment by mdyring** [comment]
> This is how it is looking now
> 
> image

Ah, yeah I was hoping that

1) We could use background color to distinguish between the two sections ("Your Stake" vs "All Validators")
2) The tables in the two sections (and ideally also input field on "All Validators") in the width

**Comment by Bitcoinera** [comment]
Looking like this:

image

**Comment by Bitcoinera** [comment]
Would be good to merge this one soon, since I need it to start with the display for #11

**Pull request merged**
