### PR TITLE
Ana/4 change default validator ordering

### LINKED ISSUE #4: Change default validator ordering
Sort by <voting power ASC, fees DESC> to make lower VP validators more visible.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4 

Working

image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Oops, I messed up here. Fixing :sweat_smile:

**Comment by Bitcoinera** [comment]
Maybe we can just simplify by changing the order here:

```
    sort: {
      property: `votingPower`,
      order: `asc`,
    },
```

**Comment by mdyring** [comment]
> Maybe we can just simplify by changing the order here:
> 
> ```
>     sort: {
>       property: `votingPower`,
>       order: `asc`,
>     },
> ```
> 
> It is many lines of code just to make every property have a different order, IMO 🤷

Yes agreed, let's do that instead. Main thing is prioritising lower VP and then the user can check the commission manually.

**Comment by Bitcoinera** [comment]
Great! Ready to go. One line change code :ok_hand:

**Pull request merged**
