### PR TITLE
Add fiat values

### LINKED ISSUE #16: Use token/fiat exchange rates in wallet
See https://github.com/e-money/em-ledger/blob/master/docs/tokens.md for token/rate specs.

- [ ] Add general support for [displaying](https://github.com/e-money/em-ledger/blob/master/docs/tokens.md#displaying-amounts) lunieCoins fiat values using the rate/token information. Might make sense to remove the stablecoins from network.js and then add them dynamically? 
- [ ] Display fiat amounts in portfolio balances
- [ ] Display fiat amounts in transactions page
- [ ] Let user input (and display) fiat amounts in the send modal forms
- [ ] When implemented, swap should also use fiat input/display

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #16 

Good to go

image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Looking good

image

**Comment by Bitcoinera** [comment]
Should I add the fiat currency selector in this PR too? I guess it is a good idea

**Comment by mdyring** [comment]
I think we can do it a nicer way, than it was done on lunie.io:

1) We shouldn't convert all balances to some "fiat" value selected in dropdown
2) Balances in a denom that have a fiat value from the API, i.e. the stablecoins, should instead of the token balance show the fiat amount
3) Other amounts, such as NGM remains as-is
3) Remove fiat column

**Comment by Bitcoinera** [comment]
I'd say it is good to go, but it also depends where we want to display fiat values. 

Maybe a good idea would be to display them in the SendModal for the stablecoins, like a disabled input below amount:

image

But it is also true that, if we are going to do the "Input the fiat value" functionality in the SendModal, it doesn't actually make that much sense. We will simply do that

**Comment by Bitcoinera** [comment]
Oops, currency is persisting across sessions... need to fix that

**Pull request merged**
