### PR TITLE
Add receive button on portfolio

### LINKED ISSUE #26: Add "Receive" button to Portfolio page
Not high priority, but lets explore.. But maybe something that could present a QR code and copyable address, similar to Ledger Live.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #26

ReceiveModal opened:

image

The Receive button next to the Send button. It could be moved next to the currency selector, since the address is always the same. But put it there first for aesthetic reasons

image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
I could also refactor to make ActionModal use the Modal component to be more consistent

**Comment by mdyring** [comment]
Thanks, looks good. I am not too crazy about the multiple "Send" and "Receive buttons" per row though, it seems a bit messy..

Could we try 
1) Regular "plain text" buttons next to the currency drop-down, named "Send" and "Receive"
2) Remove the rounder "Send" button on each row

**Comment by Bitcoinera** [comment]
I personally think it is better UX to have a distinct "Send" button. Having both action "Send" and "Receive" in one single modal, selecting from a dropdown, can get very confusing for users.

If it looks messy I think best solution is moving the Receive button on top, next to the currency selector, or down below, but have just one. "Send" could be just one button too. I am not sure. Got used to the Send buttons per row, looks quite nice to me :shrug: 
We could experiment though

**Comment by mdyring** [comment]
Ah I meant keeping two modals as today and also two buttons (send and receive), but instead of having two buttons per denom/row, just have them at the top next to currency drop down. I don’t think it add that much value that the denom is preselected when clicking send today, we support multiple denom sends anyway.

Sent from my iPhone

On 28 Dec 2020, at 13.02, Ana G. <notifications@github.com> wrote:

﻿


I personally think it is better UX to have a distinct "Send" button. Having both action "Send" and "Receive" in one single modal, selecting from a dropdown, can get very confusing for users.

If it looks messy I think best solution is moving the Receive button on top, next to the currency selector, or down below, but have just one. "Send" could be just one button too. I am not sure. Got used to the Send buttons per row, looks quite nice to me 🤷
We could experiment though

**Comment by Bitcoinera** [comment]
> Ah I meant keeping two modals as today and also two buttons (send and receive), but instead of having two buttons per denom/row, just have them at the top next to currency drop down.

OK, going to do it then

**Comment by Bitcoinera** [comment]
Wide screen view:

image



Thin screen view:

image

**Pull request merged**
