### PR TITLE
Add best price to instruments

### LINKED ISSUE #63: Swap: Add "Best Price" and show more instruments
Instruments query now return more data (best price) and also available instruments.

https://emoney.validator.network/api/market/instruments

I don't see them in the market information though, could this be because it filters those that have no last_traded @Bitcoinera ?

I think it would be great to show instruments that have either a last_price or best_price 👍

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #63 

Adds best price and fixes failing sorting in Swap

image

### CODE REVIEW

**Comment by mdyring** [comment]
Looks good, could we
1) switch "Last Price" and "Best Price" columns (Best Price first)
2) Change "Last Change" to "Last Trade" and show an empty value if there was no trade?

Then it looks perfect for a merge. 👍

**Comment by mdyring** [comment]
Ah, also looks like it by default sorts by "Last Change", seems "Pair" would be better default sort key:

image

**Comment by Bitcoinera** [comment]
> 2. Last Price is not shown even when there was a trade - there should be one in the screenshot where last trade was 14H ago.

Fixed! Thanks for catching that

**Comment by Bitcoinera** [comment]
image

**Pull request merged**
