### PR TITLE
Refactor portfolio and stake tables

### LINKED ISSUE #58: Refactor Portfolio + Stake tables
Refactors to do.
- [ ] Portfolio:

- Remove Rewards column
- Move available below Total amount

- [ ]  Stake:

- Create a separate LiValidator component, LiDelegationValidator, that includes Delegation and Rewards column
- Free Livalidator up by removing rewards and delegation
- Rename "Rewards" column as "Yield"

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #58

Stake:

image

Potfolio:

(Wide screens)

image

(Thin screens)

image

### CODE REVIEW

**Comment by mdyring** [comment]
Looks great! Almost there:

1) Please change column ordering to: Amount, Price, Allocation, Value
2) Sorting seems broken on Value, Allocation and Price. Maybe we can disable sorting on Allocation and Price as it does not seem to make a lot of sense: Price is not meaningful for sorting and Value will order Allocation as well.

image

**Comment by Bitcoinera** [comment]
All issues have been addressed:

image

**Comment by mdyring** [comment]
Thanks @Bitcoinera, looks good.

1) Would it be possible to remove some of whitespace between Amount and Price (Allocation could be wider)
2) It seems allocation calculation is off somehow. See eCHF and NGM, NGM value is lower than eCHF but has higher allocation 

image

**Comment by mdyring** [comment]
> Thanks @Bitcoinera, looks good.
> 
> 1. Would it be possible to remove some of whitespace between Amount and Price (Allocation could be wider)
> 2. It seems allocation calculation is off somehow. See eCHF and NGM, NGM value is lower than eCHF but has higher allocation
> 
> image

Ah, maybe it uses "Amount" instead of "Value" for allocation calculation..?

**Comment by Bitcoinera** [comment]
> Ah, maybe it uses "Amount" instead of "Value" for allocation calculation..?

Ah yeah, it uses Amount. Better use Value, true :+1:

**Comment by mdyring** [comment]
Minor layout issues remaining:

1) Space between Amount/Price on Portfolio page, Allocation column should take up more space if possible 
2) Earn page table seems indented/wrong width compared to other pages (both left and right side)
image
3) Create Order button should be justified to right with table
image

**Comment by Bitcoinera** [comment]
Everything fixed!

**Pull request merged**
