### PR TITLE
Support AddOrderMarketMsg

### LINKED ISSUE #56: Swap: support AddMarketOrderMsg
This would be easy and intuitive to do.

Simply the modal would contain a new field called "slippage". We can give some range or rather some options (checkboxes) that get displayed if the user selects to add some slippage.

If the order contains a slippage then it become automatically an AddMarketOrder order.

With this and together with #52 we should have all the swap functionality in the UI

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #56

image

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Seems like the fee needs to be paid in NGM?

image

**Comment by mdyring** [comment]
Looks good. I double checked in em-ledger code, and since we now have the "best price" information from the instruments, I would like the web wallet work this way: 

For market orders (slippage > 0), would it be possible to
1) Change "Amount to sell" to "Amount to sell (estimate)"
2) Disable the sell input as the amount is now calculated (see below)
3) Calculate the estimated amount to sell as: sell_amount = buy_amount / BestPrice * (1.0 + max_slippage) 
4) Still create MsgAddLimitOrder even when slippage > 0. Use the buy amount entered and the sell amount calculated..

This will provide the user the worst case price in the UI and not just an approximation. So I prefer this to using the Market order type.. Also the market order depends (and calculates) the internal limit price using the lastPrice, which can be different from bestPrice.

Hope this makes sense, otherwise I can explain it better on a call tomorrow. :-)

**Comment by Bitcoinera** [comment]
Just realized the "v-focus" directive seems broken 😕

**Comment by Bitcoinera** [comment]
This is how it is looking now

image

**Pull request merged**
